include: package:flutterando_analysis/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics-exclude:
    - test/**
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 3
    maximum-nesting-level: 5
    lines-of-code: 30
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-expanded-as-spacer
    - avoid-wrapping-in-padding
    - prefer-correct-edge-insets-constructor
    - prefer-single-widget-per-file
    - prefer-extracting-callbacks
    - avoid-dynamic
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - avoid-nested-conditional-expressions
    - avoid-unnecessary-conditionals
    - prefer-enums-by-name
    - prefer-moving-to-variable
    - prefer-static-class

linter:
  rules:
    - use_super_parameters
    - only_throw_errors
    - directives_ordering
    - prefer_relative_imports
    - prefer_const_constructors
    - use_build_context_synchronously
    - cascade_invocations: false
